using System.Text;
using GZCTF.Models;
using GZCTF.Models.Data;
using GZCTF.Services.Config;
using GZCTF.Utils;
using Microsoft.EntityFrameworkCore;

namespace GZCTF.Services;

/// <summary>
/// Renders the WireGuard server's <c>wg0.conf</c> from the <see cref="AdVpnPeer"/>
/// table and writes it to the shared <c>/wg-config</c> volume that the
/// <c>wireguard</c> sidecar watches. The sidecar's inotify loop runs
/// <c>wg syncconf</c> on every file change so peer adds/removes apply without a
/// container restart.
///
/// <para>Server keypair: generated by the sidecar's entrypoint on first boot.
/// This service reads <c>server.key</c> + <c>server.pub</c> from the same shared
/// volume; if they're missing it backs off and retries on the next tick (sidecar
/// hasn't initialized yet).</para>
///
/// <para>Config knobs (env vars, prefixed <c>Ad__Vpn__</c>):</para>
/// <list type="bullet">
///   <item><c>ConfigDir</c> — shared-volume mount (default <c>/wg-config</c>).</item>
///   <item><c>ServerEndpoint</c> — UDP endpoint clients dial (default
///         <c>127.0.0.1:51820</c> — operator must override for non-host access).</item>
///   <item><c>ClientCidr</c> — subnet for peer IPs (default <c>10.13.37.0/24</c>).</item>
///   <item><c>ListenPort</c> — server-side WG port (default <c>51820</c>).</item>
/// </list>
/// </summary>
public sealed class AdWireGuardSyncService(
    IServiceScopeFactory scopeFactory,
    AdVpnTopology topology,
    IConfiguration config,
    ILogger<AdWireGuardSyncService> logger) : BackgroundService
{
    private static readonly TimeSpan PollInterval = TimeSpan.FromSeconds(15);

    private string ConfigDir => config["Ad:Vpn:ConfigDir"] ?? "/wg-config";
    private string ClientCidr => config["Ad:Vpn:ClientCidr"] ?? "10.13.37.0/24";
    private int ListenPort => int.TryParse(config["Ad:Vpn:ListenPort"], out var p) ? p : 51820;

    private string ServerPrivKeyPath => Path.Combine(ConfigDir, "server.key");
    private string ServerPubKeyPath => Path.Combine(ConfigDir, "server.pub");
    private string Wg0ConfPath => Path.Combine(ConfigDir, "wg0.conf");

    // Compare wg0.conf textually so we only touch the file (= sidecar reload)
    // when peer set actually changed. Holds the last written content.
    private string? _lastWritten;

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        logger.SystemLog(
            $"AdWireGuardSyncService started; config dir = {ConfigDir}, reconciling every {PollInterval.TotalSeconds}s",
            TaskStatus.Pending, LogLevel.Information);

        while (!stoppingToken.IsCancellationRequested)
        {
            try
            {
                await SyncOnceAsync(stoppingToken);
            }
            catch (Exception e) when (e is not OperationCanceledException)
            {
                logger.LogErrorMessage(e, "AdWireGuardSyncService tick failed; will retry");
            }

            try { await Task.Delay(PollInterval, stoppingToken); }
            catch (OperationCanceledException) { break; }
        }
    }

    private async Task SyncOnceAsync(CancellationToken token)
    {
        if (!Directory.Exists(ConfigDir))
        {
            // Shared volume not mounted — log once and move on so the host
            // isn't spammed (the env var is intentionally optional so non-A&D
            // deployments don't need to provision wg).
            logger.LogDebug("AdWireGuardSyncService: {Dir} not present; skipping tick", ConfigDir);
            return;
        }

        if (!File.Exists(ServerPrivKeyPath))
        {
            logger.LogDebug(
                "AdWireGuardSyncService: server keypair not yet generated by sidecar (expected at {Path}); will retry",
                ServerPrivKeyPath);
            return;
        }

        var serverPriv = (await File.ReadAllTextAsync(ServerPrivKeyPath, token)).Trim();
        if (string.IsNullOrEmpty(serverPriv))
            return;

        // Discover challenge subnets + attach the sidecar to them if it isn't
        // already. Side-effect-OK: no-ops once the sidecar is up to date.
        // Doing this every tick covers the late-create case (a new
        // challenge network appears mid-event).
        await topology.GetChallengeSubnetsAsync(ConfigDir, token);

        await using var scope = scopeFactory.CreateAsyncScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var configService = scope.ServiceProvider.GetRequiredService<IConfigService>();
        var xorKey = configService.GetXorKey();

        // Authoritative membership gate: render a peer only while its
        // participation is still Accepted AND the user is still on the roster.
        // This makes member-kick / leave / suspend an automatic VPN revocation
        // within one tick — the same "still a member" guarantee the API token
        // (AdGameController) and SSH (InternalAdSshController) already enforce.
        // Without it, a kicked member's tunnel stayed live (RevokedAt is never
        // set on kick and the peer row isn't cascade-deleted), keeping full
        // network reach to every team's box for the rest of the game.
        var peers = await db.AdVpnPeers
            .Where(p => p.RevokedAt == null
                && db.Participations.Any(part =>
                    part.Id == p.ParticipationId
                    && part.Status == ParticipationStatus.Accepted
                    && part.Members.Any(m => m.UserId == p.UserId)))
            .OrderBy(p => p.Id)
            .ToListAsync(token);

        var serverIp = ResolveServerIp();

        var sb = new StringBuilder();
        sb.AppendLine("# wg0.conf — managed by GZCTF AdWireGuardSyncService. Do not edit by hand.");
        sb.AppendLine($"# {peers.Count} active peer(s)");
        // No "Generated <timestamp>" line — it would defeat the no-op dedup
        // below and cause a wg syncconf every poll tick.
        sb.AppendLine();
        sb.AppendLine("[Interface]");
        sb.AppendLine($"Address = {serverIp}/{ParsePrefix(ClientCidr)}");
        sb.AppendLine($"ListenPort = {ListenPort}");
        sb.AppendLine($"PrivateKey = {serverPriv}");
        // NAT VPN traffic source-side, not bound to a specific outbound
        // interface, so packets to challenge containers on either of the
        // -open / -isolated networks get masqueraded regardless of which
        // sidecar interface they egress through. Without this, the return
        // path is broken and clients can't reach challenge IPs.
        sb.AppendLine($"PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -s {ClientCidr} -j MASQUERADE");
        sb.AppendLine($"PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -s {ClientCidr} -j MASQUERADE");
        sb.AppendLine();

        foreach (var peer in peers)
        {
            // Unwrap the stored priv key just to validate readability; we only
            // need the *pubkey* for the server-side config (the priv goes back
            // to the client when they download their .conf).
            try { _ = AdVpnKeys.UnwrapPrivateKey(peer.PrivateKey, xorKey); }
            catch (FormatException)
            {
                logger.LogWarning(
                    "AdWireGuardSyncService: skipping peer {Id} with corrupt stored private key",
                    peer.Id);
                continue;
            }

            sb.AppendLine($"# Peer {peer.Id} — user {peer.UserId} participation {peer.ParticipationId}");
            sb.AppendLine("[Peer]");
            sb.AppendLine($"PublicKey = {peer.PublicKey}");
            sb.AppendLine($"AllowedIPs = {peer.AssignedIp}/32");
            sb.AppendLine();
        }

        var rendered = sb.ToString();

        // Skip the write if nothing changed (prevents pointless `wg syncconf`).
        if (_lastWritten == rendered && File.Exists(Wg0ConfPath))
            return;

        // Atomic write: rename is more reliable than partial-write semantics
        // for the sidecar's inotify trigger (close_write or moved_to).
        var tmp = Wg0ConfPath + ".tmp";
        await File.WriteAllTextAsync(tmp, rendered, token);
        File.Move(tmp, Wg0ConfPath, overwrite: true);
        _lastWritten = rendered;

        logger.SystemLog(
            $"AdWireGuardSyncService: wrote wg0.conf with {peers.Count} peer(s)",
            TaskStatus.Success, LogLevel.Information);
    }

    private string ResolveServerIp()
    {
        // The server lives at the .1 host of the client CIDR by convention
        // (AdVpnKeys.AssignNextIp reserves .0 + .1 for this).
        var parts = ClientCidr.Split('/');
        var baseIp = System.Net.IPAddress.Parse(parts[0]);
        var bytes = baseIp.GetAddressBytes();
        bytes[3] = (byte)(bytes[3] | 1);
        return new System.Net.IPAddress(bytes).ToString();
    }

    private static int ParsePrefix(string cidr) =>
        int.TryParse(cidr.Split('/').ElementAtOrDefault(1), out var p) ? p : 24;
}
